language: scala
sudo: required

services:
  - docker
jdk:
  - oraclejdk8
node_js:
  - node

before_script:
  - uname -r
  - node --version
  - yarn --version

jobs:
  include:
    # Backend tests
    - stage: test
      script:
        - ./scalafmt --test
        - sbt test:compile
        - sbt it:compile
        - sbt test
    # Frontend tests
    - stage: test
      install:
        - cd webui
        - yarn install
        - yarn setup
      script:
        - yarn format:validate
        - yarn compile
        - yarn test
    - stage: integration
      script:
        - . prepare-docker-builds
        - docker build -t frosner/cluster-broccoli-test docker/test/
        - sbt it:test
        - bash <(curl -s https://raw.githubusercontent.com/FRosner/http-api-tester/master/http-api-tester) -v -d http-api-tests/instance-persistence-couchdb
        - bash <(curl -s https://raw.githubusercontent.com/FRosner/http-api-tester/master/http-api-tester) -v -d http-api-tests/broccoli-only
        - bash <(curl -s https://raw.githubusercontent.com/FRosner/http-api-tester/master/http-api-tester) -v -d http-api-tests/broccoli-nomad
        - bash <(curl -s https://raw.githubusercontent.com/FRosner/http-api-tester/master/http-api-tester) -v -d http-api-tests/broccoli-nomad-consul
        - bash <(curl -s https://raw.githubusercontent.com/FRosner/http-api-tester/master/http-api-tester) -v -d http-api-tests/instance-persistence-dir
    - stage: docker
      script:
        # Publish docker image
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - sbt server/docker:publish


before_cache:
  # Delete transient files to avoid needless re-caching
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
cache:
  directories:
    # Cache SBT launcher and SBT dependencies
    - $HOME/.sbt/0.13/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    # Cache ELM stuff. In particular build-artifacts for tests to avoid needless
    # rebuilds
    - webui/elm-stuff/packages
    - webui/tests/elm-stuff/packages
    - webui/tests/elm-stuff/build-artifacts

after_success:
  - bash <(curl -s https://codecov.io/bash)
