language: scala
sudo: required
services:
  - docker
jdk:
  - oraclejdk8

script:
  - . prepare-docker-builds
  - docker build -t frosner/cluster-broccoli-test docker/test/
  - bash <(curl -s https://raw.githubusercontent.com/FRosner/http-api-tester/master/http-api-tester) -v -d http-api-tests/instance-persistence-couchdb
cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2
